site_name: Sycret
repo_url: https://github.com/OpenMined/sycret
theme:
  name: material
  features:
    - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings
# nav:
#   - "index.md"
#   - "python.md"
#   - "rust.md"
